version: '3'
services:
  php:
    build: ./php
    volumes:
      - ./src:/var/www/laravel
    depends_on:
      - db
    networks:
      - db-network
      - web-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./src/public:/var/www/laravel/public
    depends_on:
      - php
    networks:
      - web-network

  db:
    build: ./mariadb
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
    networks:
      - db-network

networks:
  web-network:
  db-network:

